### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by imonzalvo** [mercadopago/sdk-react#22]
## Description

I'm using next.js and this is the error I get when trying to use this library:

```
error - /Users/ignaciomonzalvo/projects/velox/valox-client-next/valox-client/node_modules/@mercadopago/sdk-react/index.js:1
import initMercadoPago from './mercadoPago/initMercadoPago';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)

```
## How To Reproduce
Install library on a next.js app and import it

**Comment by imonzalvo** [comment]
Hi @AdaltonLeite I just edited the comment because the error message was badly formatted.

This is the error message:
```
error - /Users/ignaciomonzalvo/projects/velox/valox-client-next/valox-client/node_modules/@mercadopago/sdk-react/index.js:1
import initMercadoPago from './mercadoPago/initMercadoPago';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)

```

I'm iusing the library as you said, but the error message appears on the import from a file on `node_modules`:

```
error - /Users/ignaciomonzalvo/projects/velox/valox-client-next/valox-client/node_modules/@mercadopago/sdk-react/index.js:1
```

That's why I can't do anything about it

**Comment by AdaltonLeite** [comment]
Let me try to simulate the problem here and get back to you. In the first comment it seemed to be this import problem.

**Comment by AdaltonLeite** [comment]
@imonzalvo I found the problem, as you are using nextJS it is rendering the bricks component on the server and at this point this library will not work, because it needs elements that are only available in the `window`. 

For this library to work in nextJs we need to tell it to disable the **serve side render** when passing the checkout code. A suggested implementation using [Dynamic import NextJS](https://nextjs.org/docs/advanced-features/dynamic-import): 

1. Isolate the method from this library in a component: 
```
// file checkoutMercadoPago.tsx
import {initMercadoPago, CardPayment} from '@mercadopago/sdk-react'

initMercadoPago('YOUR_PUBLIC_KEY')

const CheckoutMercadoPago = () => {
  return (
    <CardPayment
      initialization={{ amount: AMOUNT }}
      onSubmit={async (param) => {
        console.log(param);
      }}
    />
  );
};
export default CheckoutMercadoPago;
```
2. Import, using nextjs dynamic, this isolated component that was created in the previous step, this will not run this component on the server side and run this code the client side
```
// file index.tsx
import dynamic from 'next/dynamic'

const CheckoutMercadoPago = dynamic(() => import('./checkoutMercadoPago'), {ssr: false})

```

3. Use the dynamic import wrapper at the point where you want to add the checkout.
```

export default function Home() {
  return (
    <CheckoutMercadoPago />
  )
}
```

That way you will be able to use this lib together with NextJS. We couldn't change it to run on the server side because it needs elements that are available in the window, so it can only run on the client side.

I create a simples codeSandbox for this suggestion: [Codesandbox](https://codesandbox.io/p/sandbox/checkout-brick-nextjs-vyz4nq?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A3%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A4%7D%5D)

**Comment by imonzalvo** [comment]
Makes sense! Very clear response. Thank you!! 🙏
